(cl:in-package mavros_msgs-msg)
(cl:export '(PLANEID-VAL
          PLANEID
          TARG_PLANEID-VAL
          TARG_PLANEID
          ALTITUDE_LOCK-VAL
          ALTITUDE_LOCK
          IN_AIR-VAL
          IN_AIR
          MODE-VAL
          MODE
          ORIENTATION-VAL
          ORIENTATION
          GROUND_SPEED_NED_PARAM1-VAL
          GROUND_SPEED_NED_PARAM1
          GROUND_SPEED_NED_PARAM2-VAL
          GROUND_SPEED_NED_PARAM2
          GROUND_SPEED-VAL
          GROUND_SPEED
          GLOBAL_VEL_X-VAL
          GLOBAL_VEL_X
          GLOBAL_VEL_Y-VAL
          GLOBAL_VEL_Y
          GLOBAL_VEL_Z-VAL
          GLOBAL_VEL_Z
          AIR_SPEED-VAL
          AIR_SPEED
          WIND_ESTIMATE_X-VAL
          WIND_ESTIMATE_X
          WIND_ESTIMATE_Y-VAL
          WIND_ESTIMATE_Y
          WIND_ESTIMATE_Z-VAL
          WIND_ESTIMATE_Z
          RELATIVE_HIGHT-VAL
          RELATIVE_HIGHT
          LATITUDE-VAL
          LATITUDE
          ALTITUDE-VAL
          ALTITUDE
          LONGTITUDE-VAL
          LONGTITUDE
          RELATIVE_ALT-VAL
          RELATIVE_ALT
          NED_ALTITUDE-VAL
          NED_ALTITUDE
          NED_POS_X-VAL
          NED_POS_X
          NED_POS_Y-VAL
          NED_POS_Y
          NED_POS_Z-VAL
          NED_POS_Z
          NED_VEL_X-VAL
          NED_VEL_X
          NED_VEL_Y-VAL
          NED_VEL_Y
          NED_VEL_Z-VAL
          NED_VEL_Z
          NED_ACC_X-VAL
          NED_ACC_X
          NED_ACC_Y-VAL
          NED_ACC_Y
          NED_ACC_Z-VAL
          NED_ACC_Z
          NED_ACC-VAL
          NED_ACC
          BODY_ACC_X-VAL
          BODY_ACC_X
          BODY_ACC_Y-VAL
          BODY_ACC_Y
          BODY_ACC_Z-VAL
          BODY_ACC_Z
          BODY_ACC-VAL
          BODY_ACC
          PITCH_ANGLE-VAL
          PITCH_ANGLE
          YAW_ANGLE-VAL
          YAW_ANGLE
          ROLL_ANGLE-VAL
          ROLL_ANGLE
          BATTERY_VOLTAGE-VAL
          BATTERY_VOLTAGE
          BATTERY_PRECENTAGE-VAL
          BATTERY_PRECENTAGE
          BATTERY_CURRENT-VAL
          BATTERY_CURRENT
))