// Generated by gencpp from file mavros_msgs/Commands.msg
// DO NOT EDIT!


#ifndef MAVROS_MSGS_MESSAGE_COMMANDS_H
#define MAVROS_MSGS_MESSAGE_COMMANDS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mavros_msgs
{
template <class ContainerAllocator>
struct Commands_
{
  typedef Commands_<ContainerAllocator> Type;

  Commands_()
    : altitude(0.0)
    , yaw(0.0)
    , throttle(0.0)
    , roll(0.0)
    , pitch(0.0)  {
    }
  Commands_(const ContainerAllocator& _alloc)
    : altitude(0.0)
    , yaw(0.0)
    , throttle(0.0)
    , roll(0.0)
    , pitch(0.0)  {
  (void)_alloc;
    }



   typedef float _altitude_type;
  _altitude_type altitude;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef float _throttle_type;
  _throttle_type throttle;

   typedef float _roll_type;
  _roll_type roll;

   typedef float _pitch_type;
  _pitch_type pitch;





  typedef boost::shared_ptr< ::mavros_msgs::Commands_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavros_msgs::Commands_<ContainerAllocator> const> ConstPtr;

}; // struct Commands_

typedef ::mavros_msgs::Commands_<std::allocator<void> > Commands;

typedef boost::shared_ptr< ::mavros_msgs::Commands > CommandsPtr;
typedef boost::shared_ptr< ::mavros_msgs::Commands const> CommandsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavros_msgs::Commands_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavros_msgs::Commands_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mavros_msgs::Commands_<ContainerAllocator1> & lhs, const ::mavros_msgs::Commands_<ContainerAllocator2> & rhs)
{
  return lhs.altitude == rhs.altitude &&
    lhs.yaw == rhs.yaw &&
    lhs.throttle == rhs.throttle &&
    lhs.roll == rhs.roll &&
    lhs.pitch == rhs.pitch;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mavros_msgs::Commands_<ContainerAllocator1> & lhs, const ::mavros_msgs::Commands_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mavros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mavros_msgs::Commands_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavros_msgs::Commands_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavros_msgs::Commands_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavros_msgs::Commands_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavros_msgs::Commands_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavros_msgs::Commands_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavros_msgs::Commands_<ContainerAllocator> >
{
  static const char* value()
  {
    return "af1cda18f844353b7524568098cfa306";
  }

  static const char* value(const ::mavros_msgs::Commands_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaf1cda18f844353bULL;
  static const uint64_t static_value2 = 0x7524568098cfa306ULL;
};

template<class ContainerAllocator>
struct DataType< ::mavros_msgs::Commands_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavros_msgs/Commands";
  }

  static const char* value(const ::mavros_msgs::Commands_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavros_msgs::Commands_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Commands.msg\n"
"\n"
"float32 altitude\n"
"float32 yaw\n"
"float32 throttle\n"
"float32 roll\n"
"float32 pitch\n"
;
  }

  static const char* value(const ::mavros_msgs::Commands_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavros_msgs::Commands_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.altitude);
      stream.next(m.yaw);
      stream.next(m.throttle);
      stream.next(m.roll);
      stream.next(m.pitch);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Commands_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavros_msgs::Commands_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mavros_msgs::Commands_<ContainerAllocator>& v)
  {
    s << indent << "altitude: ";
    Printer<float>::stream(s, indent + "  ", v.altitude);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "throttle: ";
    Printer<float>::stream(s, indent + "  ", v.throttle);
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAVROS_MSGS_MESSAGE_COMMANDS_H
