// Generated by gencpp from file mavros_msgs/Formations.msg
// DO NOT EDIT!


#ifndef MAVROS_MSGS_MESSAGE_FORMATIONS_H
#define MAVROS_MSGS_MESSAGE_FORMATIONS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mavros_msgs
{
template <class ContainerAllocator>
struct Formations_
{
  typedef Formations_<ContainerAllocator> Type;

  Formations_()
    : formationShape()  {
    }
  Formations_(const ContainerAllocator& _alloc)
    : formationShape(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _formationShape_type;
  _formationShape_type formationShape;





  typedef boost::shared_ptr< ::mavros_msgs::Formations_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavros_msgs::Formations_<ContainerAllocator> const> ConstPtr;

}; // struct Formations_

typedef ::mavros_msgs::Formations_<std::allocator<void> > Formations;

typedef boost::shared_ptr< ::mavros_msgs::Formations > FormationsPtr;
typedef boost::shared_ptr< ::mavros_msgs::Formations const> FormationsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavros_msgs::Formations_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavros_msgs::Formations_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mavros_msgs::Formations_<ContainerAllocator1> & lhs, const ::mavros_msgs::Formations_<ContainerAllocator2> & rhs)
{
  return lhs.formationShape == rhs.formationShape;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mavros_msgs::Formations_<ContainerAllocator1> & lhs, const ::mavros_msgs::Formations_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mavros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mavros_msgs::Formations_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavros_msgs::Formations_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavros_msgs::Formations_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavros_msgs::Formations_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavros_msgs::Formations_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavros_msgs::Formations_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavros_msgs::Formations_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cb4dc526361d96c967f22a663f5d3a2a";
  }

  static const char* value(const ::mavros_msgs::Formations_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcb4dc526361d96c9ULL;
  static const uint64_t static_value2 = 0x67f22a663f5d3a2aULL;
};

template<class ContainerAllocator>
struct DataType< ::mavros_msgs::Formations_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavros_msgs/Formations";
  }

  static const char* value(const ::mavros_msgs::Formations_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavros_msgs::Formations_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Formations.msg\n"
"\n"
"string formationShape \n"
;
  }

  static const char* value(const ::mavros_msgs::Formations_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavros_msgs::Formations_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.formationShape);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Formations_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavros_msgs::Formations_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mavros_msgs::Formations_<ContainerAllocator>& v)
  {
    s << indent << "formationShape: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.formationShape);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAVROS_MSGS_MESSAGE_FORMATIONS_H
