// Generated by gencpp from file communication/FormationNavigator.msg
// DO NOT EDIT!


#ifndef COMMUNICATION_MESSAGE_FORMATIONNAVIGATOR_H
#define COMMUNICATION_MESSAGE_FORMATIONNAVIGATOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace communication
{
template <class ContainerAllocator>
struct FormationNavigator_
{
  typedef FormationNavigator_<ContainerAllocator> Type;

  FormationNavigator_()
    : count_number(0.0)
    , position_x(0.0)
    , position_y(0.0)
    , position_z(0.0)
    , homeLat(0.0)
    , homeLon(0.0)
    , homeAlt(0.0)
    , gps_time()
    , gap_x(0)
    , gap_y(0)
    , leaderAirspeed(0.0)
    , leaderHeading(0.0)  {
    }
  FormationNavigator_(const ContainerAllocator& _alloc)
    : count_number(0.0)
    , position_x(0.0)
    , position_y(0.0)
    , position_z(0.0)
    , homeLat(0.0)
    , homeLon(0.0)
    , homeAlt(0.0)
    , gps_time()
    , gap_x(0)
    , gap_y(0)
    , leaderAirspeed(0.0)
    , leaderHeading(0.0)  {
  (void)_alloc;
    }



   typedef double _count_number_type;
  _count_number_type count_number;

   typedef double _position_x_type;
  _position_x_type position_x;

   typedef double _position_y_type;
  _position_y_type position_y;

   typedef double _position_z_type;
  _position_z_type position_z;

   typedef double _homeLat_type;
  _homeLat_type homeLat;

   typedef double _homeLon_type;
  _homeLon_type homeLon;

   typedef double _homeAlt_type;
  _homeAlt_type homeAlt;

   typedef ros::Time _gps_time_type;
  _gps_time_type gps_time;

   typedef int32_t _gap_x_type;
  _gap_x_type gap_x;

   typedef int32_t _gap_y_type;
  _gap_y_type gap_y;

   typedef double _leaderAirspeed_type;
  _leaderAirspeed_type leaderAirspeed;

   typedef double _leaderHeading_type;
  _leaderHeading_type leaderHeading;





  typedef boost::shared_ptr< ::communication::FormationNavigator_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::communication::FormationNavigator_<ContainerAllocator> const> ConstPtr;

}; // struct FormationNavigator_

typedef ::communication::FormationNavigator_<std::allocator<void> > FormationNavigator;

typedef boost::shared_ptr< ::communication::FormationNavigator > FormationNavigatorPtr;
typedef boost::shared_ptr< ::communication::FormationNavigator const> FormationNavigatorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::communication::FormationNavigator_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::communication::FormationNavigator_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::communication::FormationNavigator_<ContainerAllocator1> & lhs, const ::communication::FormationNavigator_<ContainerAllocator2> & rhs)
{
  return lhs.count_number == rhs.count_number &&
    lhs.position_x == rhs.position_x &&
    lhs.position_y == rhs.position_y &&
    lhs.position_z == rhs.position_z &&
    lhs.homeLat == rhs.homeLat &&
    lhs.homeLon == rhs.homeLon &&
    lhs.homeAlt == rhs.homeAlt &&
    lhs.gps_time == rhs.gps_time &&
    lhs.gap_x == rhs.gap_x &&
    lhs.gap_y == rhs.gap_y &&
    lhs.leaderAirspeed == rhs.leaderAirspeed &&
    lhs.leaderHeading == rhs.leaderHeading;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::communication::FormationNavigator_<ContainerAllocator1> & lhs, const ::communication::FormationNavigator_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace communication

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::communication::FormationNavigator_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::communication::FormationNavigator_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::communication::FormationNavigator_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::communication::FormationNavigator_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::communication::FormationNavigator_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::communication::FormationNavigator_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::communication::FormationNavigator_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a05bd8f0a47698fdac1759384190f8ba";
  }

  static const char* value(const ::communication::FormationNavigator_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa05bd8f0a47698fdULL;
  static const uint64_t static_value2 = 0xac1759384190f8baULL;
};

template<class ContainerAllocator>
struct DataType< ::communication::FormationNavigator_<ContainerAllocator> >
{
  static const char* value()
  {
    return "communication/FormationNavigator";
  }

  static const char* value(const ::communication::FormationNavigator_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::communication::FormationNavigator_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# FormationNavigator.msg\n"
"\n"
"float64 count_number\n"
"float64 position_x\n"
"float64 position_y\n"
"float64 position_z\n"
"\n"
"float64 homeLat\n"
"float64 homeLon\n"
"float64 homeAlt\n"
"\n"
"time gps_time\n"
"\n"
"int32 gap_x\n"
"int32 gap_y\n"
"\n"
"float64 leaderAirspeed\n"
"float64 leaderHeading\n"
;
  }

  static const char* value(const ::communication::FormationNavigator_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::communication::FormationNavigator_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.count_number);
      stream.next(m.position_x);
      stream.next(m.position_y);
      stream.next(m.position_z);
      stream.next(m.homeLat);
      stream.next(m.homeLon);
      stream.next(m.homeAlt);
      stream.next(m.gps_time);
      stream.next(m.gap_x);
      stream.next(m.gap_y);
      stream.next(m.leaderAirspeed);
      stream.next(m.leaderHeading);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FormationNavigator_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::communication::FormationNavigator_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::communication::FormationNavigator_<ContainerAllocator>& v)
  {
    s << indent << "count_number: ";
    Printer<double>::stream(s, indent + "  ", v.count_number);
    s << indent << "position_x: ";
    Printer<double>::stream(s, indent + "  ", v.position_x);
    s << indent << "position_y: ";
    Printer<double>::stream(s, indent + "  ", v.position_y);
    s << indent << "position_z: ";
    Printer<double>::stream(s, indent + "  ", v.position_z);
    s << indent << "homeLat: ";
    Printer<double>::stream(s, indent + "  ", v.homeLat);
    s << indent << "homeLon: ";
    Printer<double>::stream(s, indent + "  ", v.homeLon);
    s << indent << "homeAlt: ";
    Printer<double>::stream(s, indent + "  ", v.homeAlt);
    s << indent << "gps_time: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.gps_time);
    s << indent << "gap_x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.gap_x);
    s << indent << "gap_y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.gap_y);
    s << indent << "leaderAirspeed: ";
    Printer<double>::stream(s, indent + "  ", v.leaderAirspeed);
    s << indent << "leaderHeading: ";
    Printer<double>::stream(s, indent + "  ", v.leaderHeading);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMUNICATION_MESSAGE_FORMATIONNAVIGATOR_H
