// Generated by gencpp from file fw_msgs/DataLinkDown.msg
// DO NOT EDIT!


#ifndef FW_MSGS_MESSAGE_DATALINKDOWN_H
#define FW_MSGS_MESSAGE_DATALINKDOWN_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fw_msgs
{
template <class ContainerAllocator>
struct DataLinkDown_
{
  typedef DataLinkDown_<ContainerAllocator> Type;

  DataLinkDown_()
    : isDataLinkDown(0)  {
    }
  DataLinkDown_(const ContainerAllocator& _alloc)
    : isDataLinkDown(0)  {
  (void)_alloc;
    }



   typedef int32_t _isDataLinkDown_type;
  _isDataLinkDown_type isDataLinkDown;





  typedef boost::shared_ptr< ::fw_msgs::DataLinkDown_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fw_msgs::DataLinkDown_<ContainerAllocator> const> ConstPtr;

}; // struct DataLinkDown_

typedef ::fw_msgs::DataLinkDown_<std::allocator<void> > DataLinkDown;

typedef boost::shared_ptr< ::fw_msgs::DataLinkDown > DataLinkDownPtr;
typedef boost::shared_ptr< ::fw_msgs::DataLinkDown const> DataLinkDownConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fw_msgs::DataLinkDown_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fw_msgs::DataLinkDown_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fw_msgs::DataLinkDown_<ContainerAllocator1> & lhs, const ::fw_msgs::DataLinkDown_<ContainerAllocator2> & rhs)
{
  return lhs.isDataLinkDown == rhs.isDataLinkDown;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fw_msgs::DataLinkDown_<ContainerAllocator1> & lhs, const ::fw_msgs::DataLinkDown_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fw_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::fw_msgs::DataLinkDown_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fw_msgs::DataLinkDown_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fw_msgs::DataLinkDown_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fw_msgs::DataLinkDown_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fw_msgs::DataLinkDown_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fw_msgs::DataLinkDown_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fw_msgs::DataLinkDown_<ContainerAllocator> >
{
  static const char* value()
  {
    return "27e3a3f98f0830d328812cc2b4a61f31";
  }

  static const char* value(const ::fw_msgs::DataLinkDown_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x27e3a3f98f0830d3ULL;
  static const uint64_t static_value2 = 0x28812cc2b4a61f31ULL;
};

template<class ContainerAllocator>
struct DataType< ::fw_msgs::DataLinkDown_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fw_msgs/DataLinkDown";
  }

  static const char* value(const ::fw_msgs::DataLinkDown_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fw_msgs::DataLinkDown_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# DataLinkDown.msg\n"
"\n"
"int32 isDataLinkDown\n"
"\n"
"# \"communication/dataLinkDown/isBreak\"\n"
;
  }

  static const char* value(const ::fw_msgs::DataLinkDown_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fw_msgs::DataLinkDown_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.isDataLinkDown);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DataLinkDown_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fw_msgs::DataLinkDown_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fw_msgs::DataLinkDown_<ContainerAllocator>& v)
  {
    s << indent << "isDataLinkDown: ";
    Printer<int32_t>::stream(s, indent + "  ", v.isDataLinkDown);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FW_MSGS_MESSAGE_DATALINKDOWN_H
