// Generated by gencpp from file fw_msgs/EXITflag.msg
// DO NOT EDIT!


#ifndef FW_MSGS_MESSAGE_EXITFLAG_H
#define FW_MSGS_MESSAGE_EXITFLAG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fw_msgs
{
template <class ContainerAllocator>
struct EXITflag_
{
  typedef EXITflag_<ContainerAllocator> Type;

  EXITflag_()
    : EXIT_FLAG(0)  {
    }
  EXITflag_(const ContainerAllocator& _alloc)
    : EXIT_FLAG(0)  {
  (void)_alloc;
    }



   typedef int32_t _EXIT_FLAG_type;
  _EXIT_FLAG_type EXIT_FLAG;





  typedef boost::shared_ptr< ::fw_msgs::EXITflag_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fw_msgs::EXITflag_<ContainerAllocator> const> ConstPtr;

}; // struct EXITflag_

typedef ::fw_msgs::EXITflag_<std::allocator<void> > EXITflag;

typedef boost::shared_ptr< ::fw_msgs::EXITflag > EXITflagPtr;
typedef boost::shared_ptr< ::fw_msgs::EXITflag const> EXITflagConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fw_msgs::EXITflag_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fw_msgs::EXITflag_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fw_msgs::EXITflag_<ContainerAllocator1> & lhs, const ::fw_msgs::EXITflag_<ContainerAllocator2> & rhs)
{
  return lhs.EXIT_FLAG == rhs.EXIT_FLAG;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fw_msgs::EXITflag_<ContainerAllocator1> & lhs, const ::fw_msgs::EXITflag_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fw_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::fw_msgs::EXITflag_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fw_msgs::EXITflag_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fw_msgs::EXITflag_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fw_msgs::EXITflag_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fw_msgs::EXITflag_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fw_msgs::EXITflag_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fw_msgs::EXITflag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eef81bba155a9b445b2c20263a5058af";
  }

  static const char* value(const ::fw_msgs::EXITflag_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeef81bba155a9b44ULL;
  static const uint64_t static_value2 = 0x5b2c20263a5058afULL;
};

template<class ContainerAllocator>
struct DataType< ::fw_msgs::EXITflag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fw_msgs/EXITflag";
  }

  static const char* value(const ::fw_msgs::EXITflag_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fw_msgs::EXITflag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# EXITflag.msg\n"
"\n"
"int32 EXIT_FLAG\n"
"\n"
"# 0: 正常      1: 退出\n"
"# uavName + \"communication/exitFlag/exitflag\"\n"
;
  }

  static const char* value(const ::fw_msgs::EXITflag_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fw_msgs::EXITflag_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.EXIT_FLAG);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EXITflag_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fw_msgs::EXITflag_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fw_msgs::EXITflag_<ContainerAllocator>& v)
  {
    s << indent << "EXIT_FLAG: ";
    Printer<int32_t>::stream(s, indent + "  ", v.EXIT_FLAG);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FW_MSGS_MESSAGE_EXITFLAG_H
