// Generated by gencpp from file fw_msgs/flyMode.msg
// DO NOT EDIT!


#ifndef FW_MSGS_MESSAGE_FLYMODE_H
#define FW_MSGS_MESSAGE_FLYMODE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fw_msgs
{
template <class ContainerAllocator>
struct flyMode_
{
  typedef flyMode_<ContainerAllocator> Type;

  flyMode_()
    : IsSingleMode(0.0)
    , ControlMode(0.0)  {
    }
  flyMode_(const ContainerAllocator& _alloc)
    : IsSingleMode(0.0)
    , ControlMode(0.0)  {
  (void)_alloc;
    }



   typedef double _IsSingleMode_type;
  _IsSingleMode_type IsSingleMode;

   typedef double _ControlMode_type;
  _ControlMode_type ControlMode;





  typedef boost::shared_ptr< ::fw_msgs::flyMode_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fw_msgs::flyMode_<ContainerAllocator> const> ConstPtr;

}; // struct flyMode_

typedef ::fw_msgs::flyMode_<std::allocator<void> > flyMode;

typedef boost::shared_ptr< ::fw_msgs::flyMode > flyModePtr;
typedef boost::shared_ptr< ::fw_msgs::flyMode const> flyModeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fw_msgs::flyMode_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fw_msgs::flyMode_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fw_msgs::flyMode_<ContainerAllocator1> & lhs, const ::fw_msgs::flyMode_<ContainerAllocator2> & rhs)
{
  return lhs.IsSingleMode == rhs.IsSingleMode &&
    lhs.ControlMode == rhs.ControlMode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fw_msgs::flyMode_<ContainerAllocator1> & lhs, const ::fw_msgs::flyMode_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fw_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::fw_msgs::flyMode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fw_msgs::flyMode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fw_msgs::flyMode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fw_msgs::flyMode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fw_msgs::flyMode_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fw_msgs::flyMode_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fw_msgs::flyMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8bbfbbef36e847700d30280b89afcfb1";
  }

  static const char* value(const ::fw_msgs::flyMode_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8bbfbbef36e84770ULL;
  static const uint64_t static_value2 = 0x0d30280b89afcfb1ULL;
};

template<class ContainerAllocator>
struct DataType< ::fw_msgs::flyMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fw_msgs/flyMode";
  }

  static const char* value(const ::fw_msgs::flyMode_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fw_msgs::flyMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# flyMode.msg\n"
"\n"
"float64 IsSingleMode\n"
"float64 ControlMode\n"
;
  }

  static const char* value(const ::fw_msgs::flyMode_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fw_msgs::flyMode_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.IsSingleMode);
      stream.next(m.ControlMode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct flyMode_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fw_msgs::flyMode_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fw_msgs::flyMode_<ContainerAllocator>& v)
  {
    s << indent << "IsSingleMode: ";
    Printer<double>::stream(s, indent + "  ", v.IsSingleMode);
    s << indent << "ControlMode: ";
    Printer<double>::stream(s, indent + "  ", v.ControlMode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FW_MSGS_MESSAGE_FLYMODE_H
