// Generated by gencpp from file fw_msgs/ModeSetting.msg
// DO NOT EDIT!


#ifndef FW_MSGS_MESSAGE_MODESETTING_H
#define FW_MSGS_MESSAGE_MODESETTING_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fw_msgs
{
template <class ContainerAllocator>
struct ModeSetting_
{
  typedef ModeSetting_<ContainerAllocator> Type;

  ModeSetting_()
    : Mode(0.0)  {
    }
  ModeSetting_(const ContainerAllocator& _alloc)
    : Mode(0.0)  {
  (void)_alloc;
    }



   typedef double _Mode_type;
  _Mode_type Mode;





  typedef boost::shared_ptr< ::fw_msgs::ModeSetting_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fw_msgs::ModeSetting_<ContainerAllocator> const> ConstPtr;

}; // struct ModeSetting_

typedef ::fw_msgs::ModeSetting_<std::allocator<void> > ModeSetting;

typedef boost::shared_ptr< ::fw_msgs::ModeSetting > ModeSettingPtr;
typedef boost::shared_ptr< ::fw_msgs::ModeSetting const> ModeSettingConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fw_msgs::ModeSetting_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fw_msgs::ModeSetting_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fw_msgs::ModeSetting_<ContainerAllocator1> & lhs, const ::fw_msgs::ModeSetting_<ContainerAllocator2> & rhs)
{
  return lhs.Mode == rhs.Mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fw_msgs::ModeSetting_<ContainerAllocator1> & lhs, const ::fw_msgs::ModeSetting_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fw_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::fw_msgs::ModeSetting_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fw_msgs::ModeSetting_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fw_msgs::ModeSetting_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fw_msgs::ModeSetting_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fw_msgs::ModeSetting_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fw_msgs::ModeSetting_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fw_msgs::ModeSetting_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fa9a51763d03303f4394bfc6178f2b70";
  }

  static const char* value(const ::fw_msgs::ModeSetting_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfa9a51763d03303fULL;
  static const uint64_t static_value2 = 0x4394bfc6178f2b70ULL;
};

template<class ContainerAllocator>
struct DataType< ::fw_msgs::ModeSetting_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fw_msgs/ModeSetting";
  }

  static const char* value(const ::fw_msgs::ModeSetting_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fw_msgs::ModeSetting_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ModeSetting.msg\n"
"\n"
"float64 Mode\n"
;
  }

  static const char* value(const ::fw_msgs::ModeSetting_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fw_msgs::ModeSetting_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ModeSetting_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fw_msgs::ModeSetting_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fw_msgs::ModeSetting_<ContainerAllocator>& v)
  {
    s << indent << "Mode: ";
    Printer<double>::stream(s, indent + "  ", v.Mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FW_MSGS_MESSAGE_MODESETTING_H
