// Generated by gencpp from file fw_msgs/target.msg
// DO NOT EDIT!


#ifndef FW_MSGS_MESSAGE_TARGET_H
#define FW_MSGS_MESSAGE_TARGET_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fw_msgs
{
template <class ContainerAllocator>
struct target_
{
  typedef target_<ContainerAllocator> Type;

  target_()
    : targetid(0)
    , latitude(0.0)
    , longitude(0.0)
    , altitude(0.0)  {
    }
  target_(const ContainerAllocator& _alloc)
    : targetid(0)
    , latitude(0.0)
    , longitude(0.0)
    , altitude(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _targetid_type;
  _targetid_type targetid;

   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _longitude_type;
  _longitude_type longitude;

   typedef double _altitude_type;
  _altitude_type altitude;





  typedef boost::shared_ptr< ::fw_msgs::target_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fw_msgs::target_<ContainerAllocator> const> ConstPtr;

}; // struct target_

typedef ::fw_msgs::target_<std::allocator<void> > target;

typedef boost::shared_ptr< ::fw_msgs::target > targetPtr;
typedef boost::shared_ptr< ::fw_msgs::target const> targetConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fw_msgs::target_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fw_msgs::target_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fw_msgs::target_<ContainerAllocator1> & lhs, const ::fw_msgs::target_<ContainerAllocator2> & rhs)
{
  return lhs.targetid == rhs.targetid &&
    lhs.latitude == rhs.latitude &&
    lhs.longitude == rhs.longitude &&
    lhs.altitude == rhs.altitude;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fw_msgs::target_<ContainerAllocator1> & lhs, const ::fw_msgs::target_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fw_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::fw_msgs::target_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fw_msgs::target_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fw_msgs::target_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fw_msgs::target_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fw_msgs::target_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fw_msgs::target_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fw_msgs::target_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0ec4af83b47a479a022174259329355a";
  }

  static const char* value(const ::fw_msgs::target_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0ec4af83b47a479aULL;
  static const uint64_t static_value2 = 0x022174259329355aULL;
};

template<class ContainerAllocator>
struct DataType< ::fw_msgs::target_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fw_msgs/target";
  }

  static const char* value(const ::fw_msgs::target_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fw_msgs::target_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# target.msg\n"
"\n"
"int32 targetid\n"
"float64 latitude\n"
"float64 longitude\n"
"float64 altitude\n"
;
  }

  static const char* value(const ::fw_msgs::target_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fw_msgs::target_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.targetid);
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.altitude);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct target_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fw_msgs::target_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fw_msgs::target_<ContainerAllocator>& v)
  {
    s << indent << "targetid: ";
    Printer<int32_t>::stream(s, indent + "  ", v.targetid);
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    s << indent << "altitude: ";
    Printer<double>::stream(s, indent + "  ", v.altitude);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FW_MSGS_MESSAGE_TARGET_H
