# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from fw_msgs/position_setpoint_triplet.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import mavros_msgs.msg

class position_setpoint_triplet(genpy.Message):
  _md5sum = "5c2856e9a0135c7692129a603be86694"
  _type = "fw_msgs/position_setpoint_triplet"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# position_setpoint_triplet.msg

float64 count_number
float64 selforgheading
mavros_msgs/Waypoint currentWaypoint
mavros_msgs/Waypoint nextWaypoint
mavros_msgs/Waypoint enu_currentWaypoint
mavros_msgs/Waypoint enu_nextWaypoint
int8 Throttle
int8 ExistNext

================================================================================
MSG: mavros_msgs/Waypoint
# Waypoint.msg
#
# ROS representation of MAVLink MISSION_ITEM
# See mavlink documentation



# see enum MAV_FRAME
uint8 frame
uint8 FRAME_GLOBAL = 0
uint8 FRAME_LOCAL_NED = 1
uint8 FRAME_MISSION = 2
uint8 FRAME_GLOBAL_REL_ALT = 3
uint8 FRAME_LOCAL_ENU = 4

# see enum MAV_CMD and CommandCode.msg
uint16 command

bool is_current
bool autocontinue
# meaning of this params described in enum MAV_CMD
float32 param1
float32 param2
float32 param3
float32 param4
float64 x_lat
float64 y_long
float64 z_alt
"""
  __slots__ = ['count_number','selforgheading','currentWaypoint','nextWaypoint','enu_currentWaypoint','enu_nextWaypoint','Throttle','ExistNext']
  _slot_types = ['float64','float64','mavros_msgs/Waypoint','mavros_msgs/Waypoint','mavros_msgs/Waypoint','mavros_msgs/Waypoint','int8','int8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       count_number,selforgheading,currentWaypoint,nextWaypoint,enu_currentWaypoint,enu_nextWaypoint,Throttle,ExistNext

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(position_setpoint_triplet, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.count_number is None:
        self.count_number = 0.
      if self.selforgheading is None:
        self.selforgheading = 0.
      if self.currentWaypoint is None:
        self.currentWaypoint = mavros_msgs.msg.Waypoint()
      if self.nextWaypoint is None:
        self.nextWaypoint = mavros_msgs.msg.Waypoint()
      if self.enu_currentWaypoint is None:
        self.enu_currentWaypoint = mavros_msgs.msg.Waypoint()
      if self.enu_nextWaypoint is None:
        self.enu_nextWaypoint = mavros_msgs.msg.Waypoint()
      if self.Throttle is None:
        self.Throttle = 0
      if self.ExistNext is None:
        self.ExistNext = 0
    else:
      self.count_number = 0.
      self.selforgheading = 0.
      self.currentWaypoint = mavros_msgs.msg.Waypoint()
      self.nextWaypoint = mavros_msgs.msg.Waypoint()
      self.enu_currentWaypoint = mavros_msgs.msg.Waypoint()
      self.enu_nextWaypoint = mavros_msgs.msg.Waypoint()
      self.Throttle = 0
      self.ExistNext = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2dBH2B4f3dBH2B4f3dBH2B4f3dBH2B4f3d2b().pack(_x.count_number, _x.selforgheading, _x.currentWaypoint.frame, _x.currentWaypoint.command, _x.currentWaypoint.is_current, _x.currentWaypoint.autocontinue, _x.currentWaypoint.param1, _x.currentWaypoint.param2, _x.currentWaypoint.param3, _x.currentWaypoint.param4, _x.currentWaypoint.x_lat, _x.currentWaypoint.y_long, _x.currentWaypoint.z_alt, _x.nextWaypoint.frame, _x.nextWaypoint.command, _x.nextWaypoint.is_current, _x.nextWaypoint.autocontinue, _x.nextWaypoint.param1, _x.nextWaypoint.param2, _x.nextWaypoint.param3, _x.nextWaypoint.param4, _x.nextWaypoint.x_lat, _x.nextWaypoint.y_long, _x.nextWaypoint.z_alt, _x.enu_currentWaypoint.frame, _x.enu_currentWaypoint.command, _x.enu_currentWaypoint.is_current, _x.enu_currentWaypoint.autocontinue, _x.enu_currentWaypoint.param1, _x.enu_currentWaypoint.param2, _x.enu_currentWaypoint.param3, _x.enu_currentWaypoint.param4, _x.enu_currentWaypoint.x_lat, _x.enu_currentWaypoint.y_long, _x.enu_currentWaypoint.z_alt, _x.enu_nextWaypoint.frame, _x.enu_nextWaypoint.command, _x.enu_nextWaypoint.is_current, _x.enu_nextWaypoint.autocontinue, _x.enu_nextWaypoint.param1, _x.enu_nextWaypoint.param2, _x.enu_nextWaypoint.param3, _x.enu_nextWaypoint.param4, _x.enu_nextWaypoint.x_lat, _x.enu_nextWaypoint.y_long, _x.enu_nextWaypoint.z_alt, _x.Throttle, _x.ExistNext))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.currentWaypoint is None:
        self.currentWaypoint = mavros_msgs.msg.Waypoint()
      if self.nextWaypoint is None:
        self.nextWaypoint = mavros_msgs.msg.Waypoint()
      if self.enu_currentWaypoint is None:
        self.enu_currentWaypoint = mavros_msgs.msg.Waypoint()
      if self.enu_nextWaypoint is None:
        self.enu_nextWaypoint = mavros_msgs.msg.Waypoint()
      end = 0
      _x = self
      start = end
      end += 198
      (_x.count_number, _x.selforgheading, _x.currentWaypoint.frame, _x.currentWaypoint.command, _x.currentWaypoint.is_current, _x.currentWaypoint.autocontinue, _x.currentWaypoint.param1, _x.currentWaypoint.param2, _x.currentWaypoint.param3, _x.currentWaypoint.param4, _x.currentWaypoint.x_lat, _x.currentWaypoint.y_long, _x.currentWaypoint.z_alt, _x.nextWaypoint.frame, _x.nextWaypoint.command, _x.nextWaypoint.is_current, _x.nextWaypoint.autocontinue, _x.nextWaypoint.param1, _x.nextWaypoint.param2, _x.nextWaypoint.param3, _x.nextWaypoint.param4, _x.nextWaypoint.x_lat, _x.nextWaypoint.y_long, _x.nextWaypoint.z_alt, _x.enu_currentWaypoint.frame, _x.enu_currentWaypoint.command, _x.enu_currentWaypoint.is_current, _x.enu_currentWaypoint.autocontinue, _x.enu_currentWaypoint.param1, _x.enu_currentWaypoint.param2, _x.enu_currentWaypoint.param3, _x.enu_currentWaypoint.param4, _x.enu_currentWaypoint.x_lat, _x.enu_currentWaypoint.y_long, _x.enu_currentWaypoint.z_alt, _x.enu_nextWaypoint.frame, _x.enu_nextWaypoint.command, _x.enu_nextWaypoint.is_current, _x.enu_nextWaypoint.autocontinue, _x.enu_nextWaypoint.param1, _x.enu_nextWaypoint.param2, _x.enu_nextWaypoint.param3, _x.enu_nextWaypoint.param4, _x.enu_nextWaypoint.x_lat, _x.enu_nextWaypoint.y_long, _x.enu_nextWaypoint.z_alt, _x.Throttle, _x.ExistNext,) = _get_struct_2dBH2B4f3dBH2B4f3dBH2B4f3dBH2B4f3d2b().unpack(str[start:end])
      self.currentWaypoint.is_current = bool(self.currentWaypoint.is_current)
      self.currentWaypoint.autocontinue = bool(self.currentWaypoint.autocontinue)
      self.nextWaypoint.is_current = bool(self.nextWaypoint.is_current)
      self.nextWaypoint.autocontinue = bool(self.nextWaypoint.autocontinue)
      self.enu_currentWaypoint.is_current = bool(self.enu_currentWaypoint.is_current)
      self.enu_currentWaypoint.autocontinue = bool(self.enu_currentWaypoint.autocontinue)
      self.enu_nextWaypoint.is_current = bool(self.enu_nextWaypoint.is_current)
      self.enu_nextWaypoint.autocontinue = bool(self.enu_nextWaypoint.autocontinue)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2dBH2B4f3dBH2B4f3dBH2B4f3dBH2B4f3d2b().pack(_x.count_number, _x.selforgheading, _x.currentWaypoint.frame, _x.currentWaypoint.command, _x.currentWaypoint.is_current, _x.currentWaypoint.autocontinue, _x.currentWaypoint.param1, _x.currentWaypoint.param2, _x.currentWaypoint.param3, _x.currentWaypoint.param4, _x.currentWaypoint.x_lat, _x.currentWaypoint.y_long, _x.currentWaypoint.z_alt, _x.nextWaypoint.frame, _x.nextWaypoint.command, _x.nextWaypoint.is_current, _x.nextWaypoint.autocontinue, _x.nextWaypoint.param1, _x.nextWaypoint.param2, _x.nextWaypoint.param3, _x.nextWaypoint.param4, _x.nextWaypoint.x_lat, _x.nextWaypoint.y_long, _x.nextWaypoint.z_alt, _x.enu_currentWaypoint.frame, _x.enu_currentWaypoint.command, _x.enu_currentWaypoint.is_current, _x.enu_currentWaypoint.autocontinue, _x.enu_currentWaypoint.param1, _x.enu_currentWaypoint.param2, _x.enu_currentWaypoint.param3, _x.enu_currentWaypoint.param4, _x.enu_currentWaypoint.x_lat, _x.enu_currentWaypoint.y_long, _x.enu_currentWaypoint.z_alt, _x.enu_nextWaypoint.frame, _x.enu_nextWaypoint.command, _x.enu_nextWaypoint.is_current, _x.enu_nextWaypoint.autocontinue, _x.enu_nextWaypoint.param1, _x.enu_nextWaypoint.param2, _x.enu_nextWaypoint.param3, _x.enu_nextWaypoint.param4, _x.enu_nextWaypoint.x_lat, _x.enu_nextWaypoint.y_long, _x.enu_nextWaypoint.z_alt, _x.Throttle, _x.ExistNext))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.currentWaypoint is None:
        self.currentWaypoint = mavros_msgs.msg.Waypoint()
      if self.nextWaypoint is None:
        self.nextWaypoint = mavros_msgs.msg.Waypoint()
      if self.enu_currentWaypoint is None:
        self.enu_currentWaypoint = mavros_msgs.msg.Waypoint()
      if self.enu_nextWaypoint is None:
        self.enu_nextWaypoint = mavros_msgs.msg.Waypoint()
      end = 0
      _x = self
      start = end
      end += 198
      (_x.count_number, _x.selforgheading, _x.currentWaypoint.frame, _x.currentWaypoint.command, _x.currentWaypoint.is_current, _x.currentWaypoint.autocontinue, _x.currentWaypoint.param1, _x.currentWaypoint.param2, _x.currentWaypoint.param3, _x.currentWaypoint.param4, _x.currentWaypoint.x_lat, _x.currentWaypoint.y_long, _x.currentWaypoint.z_alt, _x.nextWaypoint.frame, _x.nextWaypoint.command, _x.nextWaypoint.is_current, _x.nextWaypoint.autocontinue, _x.nextWaypoint.param1, _x.nextWaypoint.param2, _x.nextWaypoint.param3, _x.nextWaypoint.param4, _x.nextWaypoint.x_lat, _x.nextWaypoint.y_long, _x.nextWaypoint.z_alt, _x.enu_currentWaypoint.frame, _x.enu_currentWaypoint.command, _x.enu_currentWaypoint.is_current, _x.enu_currentWaypoint.autocontinue, _x.enu_currentWaypoint.param1, _x.enu_currentWaypoint.param2, _x.enu_currentWaypoint.param3, _x.enu_currentWaypoint.param4, _x.enu_currentWaypoint.x_lat, _x.enu_currentWaypoint.y_long, _x.enu_currentWaypoint.z_alt, _x.enu_nextWaypoint.frame, _x.enu_nextWaypoint.command, _x.enu_nextWaypoint.is_current, _x.enu_nextWaypoint.autocontinue, _x.enu_nextWaypoint.param1, _x.enu_nextWaypoint.param2, _x.enu_nextWaypoint.param3, _x.enu_nextWaypoint.param4, _x.enu_nextWaypoint.x_lat, _x.enu_nextWaypoint.y_long, _x.enu_nextWaypoint.z_alt, _x.Throttle, _x.ExistNext,) = _get_struct_2dBH2B4f3dBH2B4f3dBH2B4f3dBH2B4f3d2b().unpack(str[start:end])
      self.currentWaypoint.is_current = bool(self.currentWaypoint.is_current)
      self.currentWaypoint.autocontinue = bool(self.currentWaypoint.autocontinue)
      self.nextWaypoint.is_current = bool(self.nextWaypoint.is_current)
      self.nextWaypoint.autocontinue = bool(self.nextWaypoint.autocontinue)
      self.enu_currentWaypoint.is_current = bool(self.enu_currentWaypoint.is_current)
      self.enu_currentWaypoint.autocontinue = bool(self.enu_currentWaypoint.autocontinue)
      self.enu_nextWaypoint.is_current = bool(self.enu_nextWaypoint.is_current)
      self.enu_nextWaypoint.autocontinue = bool(self.enu_nextWaypoint.autocontinue)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2dBH2B4f3dBH2B4f3dBH2B4f3dBH2B4f3d2b = None
def _get_struct_2dBH2B4f3dBH2B4f3dBH2B4f3dBH2B4f3d2b():
    global _struct_2dBH2B4f3dBH2B4f3dBH2B4f3dBH2B4f3d2b
    if _struct_2dBH2B4f3dBH2B4f3dBH2B4f3dBH2B4f3d2b is None:
        _struct_2dBH2B4f3dBH2B4f3dBH2B4f3dBH2B4f3d2b = struct.Struct("<2dBH2B4f3dBH2B4f3dBH2B4f3dBH2B4f3d2b")
    return _struct_2dBH2B4f3dBH2B4f3dBH2B4f3dBH2B4f3d2b
