# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from fw_msgs/uavflag.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class uavflag(genpy.Message):
  _md5sum = "c1082356661093bc9487862125a2ea71"
  _type = "fw_msgs/uavflag"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# uavflag.msg

float32 group
float32 isleader
float32 leaderid
float32 myid
float32 gapx
float32 gapy
float32 controlmode"""
  __slots__ = ['group','isleader','leaderid','myid','gapx','gapy','controlmode']
  _slot_types = ['float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       group,isleader,leaderid,myid,gapx,gapy,controlmode

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(uavflag, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.group is None:
        self.group = 0.
      if self.isleader is None:
        self.isleader = 0.
      if self.leaderid is None:
        self.leaderid = 0.
      if self.myid is None:
        self.myid = 0.
      if self.gapx is None:
        self.gapx = 0.
      if self.gapy is None:
        self.gapy = 0.
      if self.controlmode is None:
        self.controlmode = 0.
    else:
      self.group = 0.
      self.isleader = 0.
      self.leaderid = 0.
      self.myid = 0.
      self.gapx = 0.
      self.gapy = 0.
      self.controlmode = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_7f().pack(_x.group, _x.isleader, _x.leaderid, _x.myid, _x.gapx, _x.gapy, _x.controlmode))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 28
      (_x.group, _x.isleader, _x.leaderid, _x.myid, _x.gapx, _x.gapy, _x.controlmode,) = _get_struct_7f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_7f().pack(_x.group, _x.isleader, _x.leaderid, _x.myid, _x.gapx, _x.gapy, _x.controlmode))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 28
      (_x.group, _x.isleader, _x.leaderid, _x.myid, _x.gapx, _x.gapy, _x.controlmode,) = _get_struct_7f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7f = None
def _get_struct_7f():
    global _struct_7f
    if _struct_7f is None:
        _struct_7f = struct.Struct("<7f")
    return _struct_7f
