# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from communication/UDPData.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class UDPData(genpy.Message):
  _md5sum = "1ff2b4674f767520061c38046240545f"
  _type = "communication/UDPData"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# UDPMessage.msg

int64 number
uint16 messageid
uint16 uavid
uint16 plane_state
uint16 plane_group
float64 longitudex
float64 latitudey
float64 altitudez 
float64 heading
float64 velocity
float64 commandyaw
time GPStime
int32 parity
"""
  __slots__ = ['number','messageid','uavid','plane_state','plane_group','longitudex','latitudey','altitudez','heading','velocity','commandyaw','GPStime','parity']
  _slot_types = ['int64','uint16','uint16','uint16','uint16','float64','float64','float64','float64','float64','float64','time','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       number,messageid,uavid,plane_state,plane_group,longitudex,latitudey,altitudez,heading,velocity,commandyaw,GPStime,parity

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(UDPData, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.number is None:
        self.number = 0
      if self.messageid is None:
        self.messageid = 0
      if self.uavid is None:
        self.uavid = 0
      if self.plane_state is None:
        self.plane_state = 0
      if self.plane_group is None:
        self.plane_group = 0
      if self.longitudex is None:
        self.longitudex = 0.
      if self.latitudey is None:
        self.latitudey = 0.
      if self.altitudez is None:
        self.altitudez = 0.
      if self.heading is None:
        self.heading = 0.
      if self.velocity is None:
        self.velocity = 0.
      if self.commandyaw is None:
        self.commandyaw = 0.
      if self.GPStime is None:
        self.GPStime = genpy.Time()
      if self.parity is None:
        self.parity = 0
    else:
      self.number = 0
      self.messageid = 0
      self.uavid = 0
      self.plane_state = 0
      self.plane_group = 0
      self.longitudex = 0.
      self.latitudey = 0.
      self.altitudez = 0.
      self.heading = 0.
      self.velocity = 0.
      self.commandyaw = 0.
      self.GPStime = genpy.Time()
      self.parity = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_q4H6d2Ii().pack(_x.number, _x.messageid, _x.uavid, _x.plane_state, _x.plane_group, _x.longitudex, _x.latitudey, _x.altitudez, _x.heading, _x.velocity, _x.commandyaw, _x.GPStime.secs, _x.GPStime.nsecs, _x.parity))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.GPStime is None:
        self.GPStime = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 76
      (_x.number, _x.messageid, _x.uavid, _x.plane_state, _x.plane_group, _x.longitudex, _x.latitudey, _x.altitudez, _x.heading, _x.velocity, _x.commandyaw, _x.GPStime.secs, _x.GPStime.nsecs, _x.parity,) = _get_struct_q4H6d2Ii().unpack(str[start:end])
      self.GPStime.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_q4H6d2Ii().pack(_x.number, _x.messageid, _x.uavid, _x.plane_state, _x.plane_group, _x.longitudex, _x.latitudey, _x.altitudez, _x.heading, _x.velocity, _x.commandyaw, _x.GPStime.secs, _x.GPStime.nsecs, _x.parity))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.GPStime is None:
        self.GPStime = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 76
      (_x.number, _x.messageid, _x.uavid, _x.plane_state, _x.plane_group, _x.longitudex, _x.latitudey, _x.altitudez, _x.heading, _x.velocity, _x.commandyaw, _x.GPStime.secs, _x.GPStime.nsecs, _x.parity,) = _get_struct_q4H6d2Ii().unpack(str[start:end])
      self.GPStime.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_q4H6d2Ii = None
def _get_struct_q4H6d2Ii():
    global _struct_q4H6d2Ii
    if _struct_q4H6d2Ii is None:
        _struct_q4H6d2Ii = struct.Struct("<q4H6d2Ii")
    return _struct_q4H6d2Ii
