# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from communication/UpdHP.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class UpdHP(genpy.Message):
  _md5sum = "7f25d391682710b024a661224416d7c4"
  _type = "communication/UpdHP"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# UDPMessage.msg

uint16 messageid
uint16 uavid
float64 longitude
float64 latitude
float64 altitude 
int32 parity"""
  __slots__ = ['messageid','uavid','longitude','latitude','altitude','parity']
  _slot_types = ['uint16','uint16','float64','float64','float64','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       messageid,uavid,longitude,latitude,altitude,parity

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(UpdHP, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.messageid is None:
        self.messageid = 0
      if self.uavid is None:
        self.uavid = 0
      if self.longitude is None:
        self.longitude = 0.
      if self.latitude is None:
        self.latitude = 0.
      if self.altitude is None:
        self.altitude = 0.
      if self.parity is None:
        self.parity = 0
    else:
      self.messageid = 0
      self.uavid = 0
      self.longitude = 0.
      self.latitude = 0.
      self.altitude = 0.
      self.parity = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2H3di().pack(_x.messageid, _x.uavid, _x.longitude, _x.latitude, _x.altitude, _x.parity))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.messageid, _x.uavid, _x.longitude, _x.latitude, _x.altitude, _x.parity,) = _get_struct_2H3di().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2H3di().pack(_x.messageid, _x.uavid, _x.longitude, _x.latitude, _x.altitude, _x.parity))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.messageid, _x.uavid, _x.longitude, _x.latitude, _x.altitude, _x.parity,) = _get_struct_2H3di().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2H3di = None
def _get_struct_2H3di():
    global _struct_2H3di
    if _struct_2H3di is None:
        _struct_2H3di = struct.Struct("<2H3di")
    return _struct_2H3di
