// Generated by gencpp from file test/stringMsg.msg
// DO NOT EDIT!


#ifndef TEST_MESSAGE_STRINGMSG_H
#define TEST_MESSAGE_STRINGMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test
{
template <class ContainerAllocator>
struct stringMsg_
{
  typedef stringMsg_<ContainerAllocator> Type;

  stringMsg_()
    : number(0)
    , testData1(0)
    , testData2(0)  {
    }
  stringMsg_(const ContainerAllocator& _alloc)
    : number(0)
    , testData1(0)
    , testData2(0)  {
  (void)_alloc;
    }



   typedef uint32_t _number_type;
  _number_type number;

   typedef uint32_t _testData1_type;
  _testData1_type testData1;

   typedef uint32_t _testData2_type;
  _testData2_type testData2;





  typedef boost::shared_ptr< ::test::stringMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test::stringMsg_<ContainerAllocator> const> ConstPtr;

}; // struct stringMsg_

typedef ::test::stringMsg_<std::allocator<void> > stringMsg;

typedef boost::shared_ptr< ::test::stringMsg > stringMsgPtr;
typedef boost::shared_ptr< ::test::stringMsg const> stringMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test::stringMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test::stringMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::test::stringMsg_<ContainerAllocator1> & lhs, const ::test::stringMsg_<ContainerAllocator2> & rhs)
{
  return lhs.number == rhs.number &&
    lhs.testData1 == rhs.testData1 &&
    lhs.testData2 == rhs.testData2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::test::stringMsg_<ContainerAllocator1> & lhs, const ::test::stringMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace test

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::test::stringMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test::stringMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test::stringMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test::stringMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test::stringMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test::stringMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test::stringMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ceb80582456c5541e317ccd118b86605";
  }

  static const char* value(const ::test::stringMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xceb80582456c5541ULL;
  static const uint64_t static_value2 = 0xe317ccd118b86605ULL;
};

template<class ContainerAllocator>
struct DataType< ::test::stringMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test/stringMsg";
  }

  static const char* value(const ::test::stringMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test::stringMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# stringMsg.msg\n"
"\n"
"uint32 number\n"
"uint32 testData1\n"
"uint32 testData2\n"
"\n"
;
  }

  static const char* value(const ::test::stringMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test::stringMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.number);
      stream.next(m.testData1);
      stream.next(m.testData2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct stringMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test::stringMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test::stringMsg_<ContainerAllocator>& v)
  {
    s << indent << "number: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.number);
    s << indent << "testData1: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.testData1);
    s << indent << "testData2: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.testData2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_MESSAGE_STRINGMSG_H
